replicaCount: 1

image:
  repository: balanus/weatherapp
  tag: fixedv1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

deployment:
  containerPort: 3000

APP_ID: ecbd92ff90840c3a36dad8d16f7f7fb2

productionEnv : true
productionReplicaCount: 2

APP_DEFAULT_CITY: Japan

gatewayhostname: "jp.157.230.73.84.nip.io"
gatewayport: 80